bot.name=ResumeProcessorBot
bot.token=5903799548:AAGpRXo5kOlHzuQsIgqMYaLdqh05vdXGK2k
service.file_info.uri=https://api.telegram.org/bot{token}/getFile?file_id={fileId}
service.file_storage.uri=https://api.telegram.org/file/bot{token}/{filePath}