bot.name=ResumeProcessorBot
bot.token=5903799548:AAGpRXo5kOlHzuQsIgqMYaLdqh05vdXGK2k

#db related settings

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQL94Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql = true

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/requirements
spring.datasource.username=postgres
spring.datasource.password=postgres